### ISSUE TITLE
Won't slice with simplify3d

### ISSUE THREAD

**Issue by RosaSkyer** [stockto2/desktophero#79]
It gets lots of weird open areas. Slices and prints fine with Flashforge FlashPrint.

**Comment by revfnord** [comment]
run throught windows 3dbuilder to make manifold then export stl than import into simplify3d just ran into that issue.

**Comment by NolanC3dPrintWorks** [comment]
Ran into similar with Cura and Repetier. Alternatives for Mac users - Mesh Mixer did not repair very well, but NetFab basic has been pretty successful.

**Comment by thetrebor** [comment]
Ideally we would generate meshes which need to fixing. Is this a problem
with the models or with the amalgamation?

**Comment by thetrebor** [comment]
*wouldn't need fixing

On Thu, Feb 2, 2017 at 2:56 PM Robert Maefs <
robert@argyletechnologygroup.com> wrote:

Ideally we would generate meshes which need to fixing. Is this a problem
with the models or with the amalgamation?
On Thu, Feb 2, 2017 at 2:48 PM NolanC3dPrintWorks <notifications@github.com>
wrote:

Ran into similar with Cura and Repetier. Alternatives for Mac users - Mesh
Mixer did not repair very well, but NetFab basic has been pretty successful.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stockto2/desktophero/issues/79#issuecomment-277062560>,
or mute the thread

**Comment by revfnord** [comment]
for windows users 3d builder is built in and only takes a minute to make print ready.
![01](https://cloud.githubusercontent.com/assets/25473297/22569089/dbf9f3f4-e95b-11e6-8569-16021d4d4130.jpg)
![02](https://cloud.githubusercontent.com/assets/25473297/22569088/dbf9f49e-e95b-11e6-8091-8fc9730e9ea3.jpg)
![03](https://cloud.githubusercontent.com/assets/25473297/22569090/dbfb1cc0-e95b-11e6-9b00-c0f2dfe7ce60.jpg)
![04](https://cloud.githubusercontent.com/assets/25473297/22569091/dbfe09a8-e95b-11e6-82bc-81b67a85b12e.jpg)


-------------------------------------------------------------------------------------
1. open .stl file you saved out from DesktopHero3D
2. click repair
3. scale to 30mm
4. save out as .stl or .obj

**Comment by stockto2** [comment]
DesktopHero exports characters with the different assets overlapping one another, which is not a manifold mesh. We won't focus on changing that at this point.

You are correct that the models can be fixed using a separate program. (Microsoft also provides an online service.) 

However, many printers will be able to print the character fine without fixing it first.
